### ISSUE TITLE
Adding Time Slip Late in Day Causes Slip to Roll To Next Day

### ISSUE THREAD

**Issue by cperry92** [TeeGree/goat-slips#51]
If adding timeslip late enough in the day, EST time zone is converted into UTC time on sending to the back-end which rolls the timeslip into the next day.
![image](https://user-images.githubusercontent.com/42746925/229405067-6ffe7d06-8b32-4502-8921-d88c4a50ec65.png)
![image](https://user-images.githubusercontent.com/42746925/229405377-44ca3164-0c31-4b33-abe2-2608aa6cb8d2.png)

**Comment by cperry92** [comment]
Was considering just updating the DateTImes to local date in the back-end for the server but that may not be enough. If a user is in New York and the server is in California would that cause issues? Need to look into it more.

**Comment by TeeGree** [comment]
Hey it's me from 5 hours in the future. I believe the issue should be fixed now. I just subtracted the timezone offset from the current date, since that is what is used as the basis for all other date calculations. Sorry for the delay!
